export const shopifyOrders: Record<string, string[]> = {
  'tom.glas11@gmail.com': ['arturia-spark'],
  'willpugh42@gmail.com': ['doom-racks'],
  'shardulmehta.tbot@gmail.com': ['doom-racks'],
  'ShaunGaryDonkin1988@hotmail.co.uk': ['self-ducking-effects'],
  'furia2k4@outlook.com': ['doom-racks'],
  'wgriffin@fraktured.net': ['doom-racks'],
  'jhuff416@gmail.com': ['gatekeeper-sidechain-bus'],
  'cool.boi.cringe@gmail.com': ['doom-racks'],
  'goifyhjw@gmail.com': ['doom-racks'],
  'narrelle.sprigg@gmail.com': ['self-ducking-effects'],
  'rhymetry.music@gmail.com': ['doom-racks'],
  'elo@michelsen4.dk': ['arturia-spark'],
  'mnelton@gmail.com': ['doom-racks'],
  'evilkittenzmusic@gmail.com': ['doom-racks'],
  'robbieconnery2001@gmail.com': ['doom-racks'],
  '1matthewanaya@gmail.com': ['doom-racks'],
  'sidprakash@gmail.com': ['doom-racks'],
  'fyctwkvaasjwpanfnq@bptfp.com': ['dextroid', 'analog-bubbles'],
  'techywhite@outlook.com': ['doom-racks'],
  'lee.southern@protonmail.com': ['doom-racks'],
  'rnsomusic@gmail.com': ['doom-racks'],
  'benjaminkdan@gmail.com': [
    'stock-sidechain-bus',
    'self-ducking-effects',
    'midi-note-delay',
    'gated-reverb',
    'filter-sweeper'
  ],
  'sells@fragmentaudio.com': ['doom-racks'],
  'andrebopp@googlemail.com': ['doom-racks'],
  'jacobhbryant@gmail.com': ['doom-racks'],
  'jwinstonwilliamsiii@gmail.com': ['arturia-spark'],
  'joey.michalina.mariano@gmail.com': ['midi-note-delay'],
  'catevi8195@ddwfzp.com': [
    'dextroid-fl',
    'sample-pack-1',
    'arturia-spark',
    'midi-note-delay',
    'fried-rattlesnake-sub',
    'dextroid',
    'gated-reverb',
    'analog-bubbles',
    'filter-sweeper'
  ],
  'patanet7@yahoo.com': ['fried-rattlesnake-sub', 'analog-bubbles'],
  'stuartparker604@gmail.com': ['gated-reverb', 'arturia-spark'],
  'baijusharda95@gmail.com': ['doom-racks'],
  'i_rule_all_2002@hotmail.com': ['self-ducking-effects'],
  'onelovesoundsystem808@gmail.com': ['doom-racks'],
  'stimpacksound@gmail.com': ['doom-racks'],
  'bryanhingerton@gmail.com': ['doom-racks'],
  'zarantoj@mail.gvsu.edu': ['doom-racks'],
  'relax330@aol.com': ['doom-racks'],
  'bunnyvtuber@gmail.com': ['doom-racks'],
  'saucerdrum@gmail.com': ['doom-racks'],
  'Blue.musicproducer@gmail.com': ['doom-racks'],
  'rorschach13@gmail.com': ['doom-racks'],
  'robertpatricksmyth@gmail.com': ['self-ducking-effects'],
  'demonicus923@gmail.com': ['doom-racks'],
  'roelvanochten@hotmail.com': ['self-ducking-effects'],
  'drewling64@gmail.com': ['doom-racks'],
  'brandonnardone@gmail.com': ['doom-racks'],
  'deangelis.aaron@gmail.com': ['doom-racks'],
  'coranithdestrmoth@yahoo.com': ['doom-racks'],
  'calebmaxwood@gmail.com': ['doom-racks'],
  'Jkrivoshein@gmail.com': ['doom-racks'],
  'barney430@gmail.com': ['doom-racks'],
  'jamesadamsprojects@gmail.com': ['doom-racks'],
  'darthque@gmail.com': ['doom-racks'],
  'jkam6033@gmail.com': ['doom-racks'],
  'tomwellingtom24@gmail.com': ['filter-sweeper'],
  'sam.kennedy585@gmail.com': [
    'doom-racks',
    'filter-sweeper',
    'ultimate-ableton-templates'
  ],
  'bradleyp@live.co.uk': ['filter-sweeper'],
  'jrajav@gmail.com': ['doom-racks', 'gated-reverb'],
  'djfoxx@quinnstine.com': ['doom-racks', 'mb2s-tri-reese'],
  'thallisthall@gmail.com': ['doom-racks', 'foley-glitch'],
  'brapped@gmail.com': ['doom-racks'],
  'contact@djdain.tel': ['doom-racks', 'dextroid'],
  'hunterhgalloway89@gmail.com': ['doom-racks', 'dextroid'],
  'ac_colton@outlook.com': ['doom-racks', 'foley-glitch'],
  'djdirtydan@gmail.com': [
    'foley-glitch',
    'mb2s-tri-reese',
    'mb2s-sub',
    'self-ducking-effects'
  ],
  'puddin21@googlemail.com': ['doom-racks', 'filter-sweeper'],
  'j.mcgrory73@hotmail.co.uk': ['doom-racks', 'filter-sweeper'],
  'zom6oid@gmail.com': ['doom-racks', 'analog-bubbles'],
  'lorenzo.pellegrini91@gmail.com': ['doom-racks'],
  'ch3-ch2-ch3.rock@protonmail.com': ['doom-racks', 'gated-reverb'],
  'sjannot@gmail.com': ['doom-racks', 'filter-sweeper'],
  'solemassif@gmail.com': ['doom-racks', 'midi-note-delay'],
  'robertmcdaniel978@gmail.com': ['doom-racks'],
  'kwl5228@outlook.com': ['doom-racks'],
  'heidi_viereck@hotmail.com': ['doom-racks'],
  'piikkila.timo@gmail.com': ['doom-racks'],
  'vx.kongret@gmail.com': ['doom-racks'],
  'lachlan.phillips.00@gmail.com': ['analog-bubbles', 'fried-rattlesnake-sub'],
  'zjm9184@gmail.com': ['doom-racks'],
  'ethanstgeorge26@gmail.com': [
    'gatekeeper-sidechain-bus',
    'midi-note-delay',
    'stereo-effect-racks',
    'mb2s-sub',
    'lfotool-sidechain-bus',
    'arturia-spark',
    'stock-sidechain-bus',
    'foley-glitch',
    'mb2s-sq-dream',
    'mb2s-funk-saw',
    'mb2s-tri-reese',
    'dextroid',
    'analog-bubbles',
    'sample-pack-1',
    'fried-rattlesnake-sub',
    'gated-reverb',
    'filter-sweeper',
    'self-ducking-effects',
    'atmosphere-1',
    'fried-rattlesnake-sub',
    'filter-sweeper',
    'self-ducking-effects',
    'md-808',
    'doom-racks'
  ],
  'subdarthproduction@gmail.com': ['doom-racks'],
  'billyiannaci@gmail.com': ['stereo-effect-racks'],
  'jcegger@gmail.com': [
    'atmosphere-1',
    'mb2s-sub',
    'mb2s-funk-saw',
    'mb2s-sq-dream'
  ],
  'rasserho@gmail.com': [
    'stock-sidechain-bus',
    'mb2s-tri-reese',
    'mb2s-sq-dream',
    'mb2s-sub',
    'ultimate-ableton-templates'
  ],
  'mailmail@mailimail.com': ['free-midi-racks'],
  'kghtet09@gmail.com': ['click-free-sidechain'],
  'Milandarden@ymail.com': ['sample-pack-1'],
  'migvelsousa@gmail.com': ['free-midi-racks', 'click-free-sidechain'],
  'obblio.fowler@gmail.com': ['click-free-sidechain'],
  'beau@partybros.us': ['mb2s-tri-reese'],
  'markleesymons@gmail.com': ['mb2s-sub'],
  'lukapil@hotmail.com': [
    'free-midi-racks',
    'click-free-sidechain',
    'sample-pack-1',
    'mb2s-sub'
  ],
  'thisisghostactual@tutanota.de': ['mb2s-sq-dream'],
  'new.used.music@gmail.com': ['ultimate-ableton-templates'],
  'ginsengbob@gmail.com': ['sample-pack-1'],
  'dramanbass@hotmail.com': [
    'click-free-sidechain',
    'sample-pack-1',
    'free-midi-racks'
  ],
  'caraleighmusic@gmail.com': ['sample-pack-1', 'click-free-sidechain'],
  'bohdan.pashchenkko@gmail.com': ['free-midi-racks', 'click-free-sidechain'],
  'pookster@gusclass.com': ['ultimate-ableton-templates'],
  'yuvraj_aurora@yahoo.com': ['click-free-sidechain'],
  'georgecostan15@gmail.com': ['sample-pack-1'],
  'tabloodmusic@gmail.com': ['notch-filter-lfo'],
  'markdaviddennis@gmail.com': [
    'ultimate-ableton-templates',
    'sample-pack-1',
    'click-free-sidechain',
    'free-midi-racks'
  ]
}
