import { Arimo } from 'next/font/google'

import './global.css'
import { cn } from '@websites/shared/react/lib'

import Header from '../components/header'

const arimo = Arimo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-arimo'
})

export const metadata = {
  title: 'Welcome to mikeallisonjs.com',
  description: 'Generated by create-nx-workspace'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={cn('dark', arimo.variable)}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
